@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onedir --console --icon "C:\Users\zhcgj\Desktop\123893516_bobopic.ico" --uac-admin  "C:\Users\zhcgj\Desktop\BAAHAUTO\ba.py"
pause
